
export const REMOVE_USED_COUNTRY = 'REMOVE_USED_COUNTRY';
export const ADD_USED_COUNTRY = 'ADD_USED_COUNTRY';
export const COUNT_SCORE = "COUNT_SCORE";
export const REMOVE_SCORE ="REMOVE_SCORE";
export const ADD_CHOICE_SELECTED = "ADD_CHOICE_SELECTED";
export const REMOVE_CHOICE ="REMOVE_CHOICE";